### ISSUE TITLE
登录出现报错：scripts.system.menu failed to create context. ReferenceError: Require is not defined

### ISSUE THREAD

**Issue by zhiyix** [wwsheng009/yao-amis-admin#1]
http://192.168.1.100:5099/api/__yao/login/admin
请求方法:POST
状态代码:500 Internal Server Error
返回值：message
: 
"scripts.system.menu failed to create context. ReferenceError: Require is not defined"
![image](https://github.com/wwsheng009/yao-amis-admin/assets/11610917/274ee64a-554b-4642-bff3-f2f939f1af12)

使用dockercompose部署的
  yao-amis-admin:
    image: yaoapp/yao:0.10.3-amd64-dev
    container_name: yao-amis-admin
    env_file:
     - .env
    environment:
      - TZ=Aria/Shanghai
    volumes:
      - $DATA_DIR/yao/yao-amis-admin/:/data/app
    command: ["yao", "start", "--debug"]
    # command: ["/opt/yao.sh"]
    ports:
      - "5099:5099"
      - "5077:5077"
    networks:
      edgex-network: null
    #restart: unless-stopped

**Comment by wwsheng009** [comment]
你好，这个使用了yao的最新的特性，需要使用到yao的开发版本,https://github.com/YaoApp/yao/actions/workflows/build-linux.yml

**Comment by zhiyix** [comment]
> 你好，这个使用了yao的最新的特性，需要使用到yao的开发版本,https://github.com/YaoApp/yao/actions/workflows/build-linux.yml
已经解决了
`    
  yao-amis-admin:
    image: yaoapp/yao:0.10.4-unstable-amd64-dev
    container_name: yao-amis-admin
    env_file:
     - .env
    environment:
      - TZ=Aria/Shanghai
    volumes:
      - $DATA_DIR/yao/yao-amis-admin/:/data/app
    command: ["yao", "start", "--debug"]
    ports:
      - "5799:5099"
      - "5777:5077"
    networks:
      edgex-network: null
    #restart: unless-stopped `
